spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    mail:
        host: email-smtp.eu-west-1.amazonaws.com
        port: 587
        username: AKIAIOEXEHQINVURKSUA
        password: Ajtt03mA3M6yfJ3908TwyOVH3DB28Xgsyx8JG6N9A9im
        properties:
            mail.transport.protocol: smtp
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            mail.smtp.starttls.required: true
        protocol: smtp
    thymeleaf:
        cache: true

schedule:
    cron-expression:
        check-services-health: 0 */10 * ? * *

email:
    noreply: noreply@worldcurrency.cards